name: My application Devsecops workflow
on: [push]
jobs:

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install node modules
        run: npm install
      - name: Run npm test
        run: npm test

  oast-retire:
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install Retire
        run: npm install -g retire
      - name: Run Retire
        run: retire --outputformat json --outputpath retire-output.json
        continue-on-error: true
      - name: Uplaod the output file
        uses: actions/upload-artifact@v2
        with:
          name: Output file
          path: retire-output.json
        if: always()

  oast-npm-audit:
    runs-on: ubuntu-latest
    needs: oast-retire
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v2
      - name: Install NPM
        run: npm install
      - name: Run NPM audit
        run: 
          npm audit --json | tee npm-output.json
        continue-on-error: true

      - name: Upload the output file
        uses: actions/upload-artifact@v2
        with:
          name: NPM audit output file
          path: npm-output.json
        if: always()
